apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ec2-instance
  title: Deploy EC2 Instance with Terraform
  description: Provision an AWS EC2 instance using Terraform and GitHub Actions
spec:
  owner: user:liquizar
  type: service
  parameters:
    - title: Fill in EC2 details
      required:
        - instanceName
        - region
        - osChoice
        - action
      properties:
        instanceName:
          title: EC2 Instance Name
          type: string
          description: The name for the EC2 instance
        instanceType:
          title: EC2 instance type (e.g., t2.micro)
          type: string
          description: The Type of the EC2 instance
        region:
          title: AWS Region
          type: string
          description: The AWS region where the instance will be deployed
        osChoice:
          title: OS Selection
          type: string
          description: OS selection (amazon_linux, ubuntu, windows, redhat)
          enum:
            - amazon_linux
            - ubuntu
            - windows
            - redhat
        action:
          title: Action
          type: string
          description: Apply or destroy the EC2 instance
          enum:
            - apply
            - destroy
  steps:
    - id: github-action
      name: Trigger GitHub Action
      action: github:actions:dispatch
      input:
        workflowId: manage-ec2.yaml
        repoUrl: github.com?owner=Liquizar&repo=sample-ec2-terraform-backstage
        branchOrTagName: 'main'
        workflowInputs:
          instanceName: ${{ parameters.instanceName }}
          awsRegion: ${{ parameters.region }}
          instanceType: ${{ parameters.instanceType }}
          osChoice: ${{ parameters.osChoice }}
          action: ${{ parameters.action }}
    
    - id: wait-for-workflow
      name: Wait for Workflow Completion
      action: http:fetch
      input:
        url: "https://api.github.com/repos/Liquizar/sample-ec2-terraform-backstage/actions/runs?per_page=1"
        method: GET
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: "Bearer ${{ secrets.GH_PAT }}"
        waitFor:
          intervalMs: 15000
          maxAttempts: 30
          condition: |
            response?.workflow_runs?.length > 0 &&
            response.workflow_runs[0].status === 'completed' &&
            response.workflow_runs[0].conclusion === 'success'

    - id: debug-workflow-response  # Debugging step (optional)
      name: Debug Workflow API Response
      action: debug:log
      input:
        message: |
          Workflow Runs Response: ${{ response }}

    - id: fetch-terraform-outputs
      name: Fetch Terraform Outputs Artifact
      action: http:fetch
      input:
        url: "https://api.github.com/repos/Liquizar/sample-ec2-terraform-backstage/actions/artifacts"
        method: GET
        headers:
          Accept: application/vnd.github.v3+json
          Authorization: "Bearer ${{ secrets.GH_PAT }}"
      output:
        artifact_url: |
          response?.artifacts?.find(a => a.name === 'terraform-outputs') 
          ? `https://api.github.com/repos/Liquizar/sample-ec2-terraform-backstage/actions/artifacts/${
              response.artifacts.find(a => a.name === 'terraform-outputs').id
            }/zip`
          : ''




  output:
    text:
      - title: EC2 Instance Details
        content: |
          - **Terraform Outputs Download**: [Click here to download]( ${{ steps['fetch-terraform-outputs'].output.artifact_url }} )

